apiVersion: v1
kind: Service
metadata:
  name: angular-frontend-service
spec:
  type: NodePort
  selector:
    app: angular-frontend  # Ensure this matches the label of your deployment
  ports:
    - port: 8081       # Port exposed inside the cluster
      targetPort: 80    # Port exposed by the container (NGINX default)
      nodePort: 31819   # NodePort exposed on your nodes (within the valid range)
